spring:
  application:
    name: lfy
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      force: true
pagehelper:
  page-size-zero: true
  auto-dialect: true
  offset-as-page-num: false
  reasonable: true
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml

